services:
  SFRO-state:
    container_name: SFRO-state
    image: sfro-state
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./extra_scripts:/app/extra_scripts
    environment:
      - TEMPEST_STATION_ID=174867
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - io.portainer.accesscontrol.users=agent
